### PR TITLE
Use zipfile instead of libzip

### PR DESCRIPTION
**Pull request by roblabla**
[`zipfile`](https://docs.python.org/3/library/zipfile.html) is part of the standard python library, removing the need for a separate dependency. `zipfile` works just fine, and is able to edit files inside existing ZIP archives without problems (at least on python 3.10).

### CODE REVIEW

**Comment by KOLANICH** [comment]
Thank you for the PR and for your attention to this project! `libzip` has been chosen (and its Python bindings have been implemented specifically for this project) in the hope that it can modify archives in-place without copying (that assumption turned to be wrong after I had implemented the bindings and this project, if I had known it in advance, I'd have chosen an another lib to create bindings to). Even if it doesn't do it in-place by now, I guess modifying an existing archive is still processed by it more efficiently than using python `zipfile`. I hope that somewhen `libzip` will be able to do in-place modification without copying a file. Even though that author of that lib said it is out of scope, it seems he is not against to merge the support if someone implemented it and if it is not difficult to maintain. Also I'm thinking about creating bindings to other libs capable doing in-place modification.

Using `zipfile`-like API is also a decent goal, but it'd be nice to create the bindings. In fact I have some source code doing this, but it is quite a low-priority task for me. And in the current state of that project I cannot share even the code I have already implemented, that's why [its repo](https://github.com/KOLANICH-libs/libzipfile.py) is empty by now.

**Comment by KOLANICH** [comment]
Also I think we should support old versions of Python too. For example 3.9 has dropped support of Windows 7. It is not OK to force people to buy a license for Windows 10 and buy the hardware running Windows 10 fast enough to just allow them to use this tool. `ctypes` should be available for ancient versions of Python and `libzip` bindings are ctypes-based. In order to use them one only need to obtain a compatible version of `libzip` shared lib and place it in a proper location. I'm not against this change, I'd like to integrate it somewhen.

**Comment by roblabla** [comment]
That's fair. Zipfile has been around since python 3.2 though ^^. I only mentioned py3.10 because that's the only version I tested (its behavior may be different on older python versions, I don't really know).

**Comment by KOLANICH** [comment]
> only mentioned py3.10 because that's the only version I tested (its behavior may be different on older python versions, I don't really know).

When I initially tried to implement this project, `zipfile` was not capable of replacing files. I looked in the internet and [found some solutions that felt extremily ugly and were too inefficient for me because they were just creating a new archive and copying files to it file-by-file](https://stackoverflow.com/questions/25738523/how-to-update-one-file-inside-zip-file), while I wanted to use the tool on large wheels like TensorFlow ones. Then I tried to tinker around it by creating a library inheriting `ZipFile` but some troubles have been encountered making that way useless. I was also considering using CLI tools, but it is a dirty, slow, unsafe, and error-prone way to do the job. So I started looking for high-level libs in languages other than Python that are capable to replace files in archives and that have Python bindings or usable through ctypes (to be able to create such bindings), and found `libzip`.

**Pull request closed without merging**
